// Package store provides Postgres access: the goose migrations that define
// the schema, embedded so a binary can apply them, and the compare-and-set
// helpers every state change goes through.
//
// State changes use UPDATE ... WHERE state = expected (RL-13). Legality of a
// move is decided by the transition table in package contracts before any
// SQL runs. The audit row in state_transitions is written by a database
// trigger that fires on any change to a state column and refuses the change
// when no actor has been set on the transaction, so the audit trail
// (FR-SEC10) holds even for code that bypasses the helpers. Cost events and
// state transitions are append-only: the application role has insert-only
// access to them.
//
// The privileges that make this a control apply only when the application
// connects as the conclave_app role: as a LOGIN role that is a member of it,
// or by SET ROLE conclave_app after connecting. Connecting as the database
// owner bypasses every grant. The package's own tests run as conclave_app
// for the same reason.
//
// Typed queries for the rest of the schema are generated by sqlc from visible
// SQL as later tickets need them.
package store
