// Package store provides typed Postgres access generated by sqlc from
// visible SQL, plus the goose migrations that define the schema.
//
// State changes use compare-and-set (UPDATE ... WHERE state = expected)
// against one transition table. Cost events and state transitions are
// append-only: the application role has insert-only access to them.
package store
