// Package store provides Postgres access: the goose migrations that define
// the schema, embedded so a binary can apply them, and the compare-and-set
// helpers every state change goes through.
//
// State changes use UPDATE ... WHERE state = expected AND revision =
// expected (RL-13). Legality of a move is decided by the transition table in
// package contracts before any SQL runs. The audit row in state_transitions
// is written by a database trigger that fires on any change to a state
// column and refuses the change when no actor has been set on the
// transaction, so the audit trail (FR-SEC10) holds for every database role
// short of the table owner, whether or not the change went through the
// helpers. The actor string is self-reported; the trigger also records the
// authenticated login as db_user. Cost events and state transitions are
// append-only: the application role has insert-only access to them.
//
// These grants are a control only when the application connects as a
// non-owner LOGIN role that is a member of conclave_app. SET ROLE
// conclave_app is acceptable from such a role, never from the owner: a
// connection that logged in as the owner can RESET ROLE and every grant
// evaporates. The package's tests use SET LOCAL ROLE from the owner pool as
// a stand-in for that deployment shape, which exercises the grants but not
// the login.
//
// Typed queries for the rest of the schema are generated by sqlc from visible
// SQL as later tickets need them.
package store
